name: Android App APK Build (Agentic Branch)

on:  
  push:
    branches:
      - agentic
  # Specify when you want the build to run here

jobs:
  build:
    runs-on: self-hosted
    environment: production
    steps:
      - name: Setup repo
        uses: actions/checkout@v4
        with:
          ref: agentic
      
      - name: Verify branch
        run: |
          echo "Current branch: $(git branch --show-current)"
      
      - name: Setup node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Verify Expo configuration
        run: |
          echo "Testing expo config..."
          npx expo config --json > /dev/null && echo "Expo config test passed" || echo "Expo config test failed"
          echo "Expo configuration verified successfully"

      - name: Build Android app
        run: eas build --platform android --profile preview --local --output ${{ github.workspace }}/app-release.apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ github.workspace }}/app-release.apk